services:
  esports-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esports_matches_site
    restart: always
    # Открываем порт 8000 только внутри сети Docker для Nginx
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - PANDASCORE_TOKEN=${PANDASCORE_TOKEN}
      - UTC_OFFSET=3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - esports-app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
